<?php

namespace risingsun\Translation\Tests;

use Illuminate\Support\Facades\Config;
use risingsun\Translation\TranslationService;

class AliyunTranslationServiceTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->getEnvironmentSetUp($this->app);
    }

    protected function getEnvironmentSetUp($app)
    {
        $translationDriver = env('TRANSLATION_DRIVER', 'aliyun');
        $accessKeyId = env('ALIYUN_TRANSLATION_ACCESS_KEY_ID', '');
        $accessSecret = env('ALIYUN_TRANSLATION_ACCESS_KEY_SECRET', '');
        $regionId = env('ALIYUN_TRANSLATION_REGION_ID', 'cn-hongkong');

        Config::set("Translation.default", $translationDriver);
        Config::set('Translation.channels.aliyun.accessKeyId', $accessKeyId);
        Config::set('Translation.channels.aliyun.accessSecret', $accessSecret);
        Config::set('Translation.channels.aliyun.regionId', $regionId);
    }

    public function testServiceCanBeResolvedFromContainer()
    {
        if (!empty($this)) {
            $service = $this->app->make(TranslationService::class);
        }
        $this->assertInstanceOf(TranslationService::class, $service);
    }

    public function testAliyunTranslationService()
    {
        Config::set("Translation.default", 'aliyun');
        $service = $this->app->make(TranslationService::class);
        $result = $service->translation('en', 'zh', 'hello world');
        echo "翻译结果为：" . $result;
        $this->assertEquals('你好，世界', $result);
    }

//    public function testGoogleTranslationService()
//    {
//        Config::set("Translation.default", 'google');
//        $service = $this->app->make(TranslationService::class);
//        $result = $service->translation('hello world', 'en', 'zh');
//        $this->assertEquals('你好，世界', $result);
//    }
}